debug: false
layout: sidebar # prefer to stacked
style: dark # prefer to light

url: https://jason-manuel.com
baseurl: ""

repository: jmanuel1/personal-website

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jekyll-org

exclude:
  - .literate-output/
  - vendor/ # excluded for CI (bundler gems caching)

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: jason-manuel
  # mastodon: your_username
  medium: JasonAManuel
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: JasonAManuel
  unsplash: photo_jam
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Front-end web development
    web_url: https://github.com/topics/frontend

  - name: Functional programming
    web_url: https://github.com/topics/functional-programming

  - name: Programming languages and compilers
    web_url: https://github.com/topics/compiler

  - name: Type theory
    web_url: https://github.com/topics/type-theory

  - name: Dependent types
    web_url: https://github.com/topics/dependent-types

  - name: Computational sustainability
    web_url: https://github.com/topics/computational-sustainability
