layout: sidebar # prefer to stacked
style: dark # prefer to light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: jason-manuel
  # mastodon: your_username
  medium: JasonAManuel
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  unsplash: photo_jam
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Computational sustainability
    web_url: https://www.computational-sustainability.org

  - name: Front-end web development
    web_url: https://github.com/topics/frontend

  - name: Progressive Web Apps
    web_url: https://github.com/topics/pwa
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/pwa/pwa.png
